### ISSUE TITLE
More Mission Suggestions

### ISSUE THREAD

**Issue by wingcwf** [Hyfe-JavaDebug/Battle-Pass#2]
-  Time Played ( like. 1hours/2hours/etc... )

-  Gain Exp from mob kills ( like. Get 1,000Exp from mobkills Mission complete )

-  Plugin Mission ( Shopguiplus/Shopgui+ )
   ( Sell $??? of items to shop )
   ( Sell ? item to shop ) / ( Sell ? item amount to shop )
   ( Buy ? item in shop ) / ( Buy ? item amount to shop ) 

- Plugin Mission ( Askyblock )
  ( Visit ?amount  others player island / is warps)

**Comment by ZakShearman** [comment]
Time played - might do this one.

Can you link me to where I can get the API for shop GUI plus?

Can't do the ASkyblock one as there is no API event for when a player warps to another's island: https://zak.pink/Lopsided-Heterodontosaurus-4190.png

**Comment by wingcwf** [comment]
https://www.spigotmc.org/resources/shopgui-1-7-1-14.6515/ 
( Shopgui+ Api , At the bottom of the page ) or ( https://gist.github.com/brcdev )

Askyblock
Maybe IslandEnterEvent / IslandPreTeleportEvent ( idk )

**Comment by ZakShearman** [comment]
Not going to be able to do play the due to lag issues and the like.

Those askyblock events would trigger for any user, and also not just on warp.

**Comment by ZakShearman** [comment]
Also not sure I can add shop GUI plus off that. Pretty sure I'd need a jar with the API in to work properly or maven repository 

@Hyfe-JavaDebug
