### ISSUE TITLE
CratesPlus - Mission not working

### ISSUE THREAD

**Issue by ghost** [Hyfe-JavaDebug/Battle-Pass#3]
The CratesPlus mission isn't working at all
I did everything the wiki said about setting a mission to open a crate.
However it does not seem to work, could you please add an explanation tutorial about it on the wiki or see if it is indeed a bug?

**Comment by ZakShearman** [comment]
Hi there @NikV2, what's your Spigot username and ID quickly?

**Comment by ZakShearman** [comment]
No response - issue closed.
